### ISSUE TITLE
Morning meeting

### ISSUE THREAD

**Issue by Zappat0n** [wazih237/New-york-times#5]

**Comment by SuyashFowdar** [comment]
- Fix extra width issue and center all items
- Fix 4 spaced tabs issue (from extension)
- Get proper SVG
- To-do: include the fonts

**Comment by Zappat0n** [comment]
You are having the same problem that I had.
When you pass the linter text it will give an error because there is not <h2-h6> after the <article> tag.
I would advise changing `<article>` for `<div class="article">` so it is easier to change the styles just from "article" to ".article".
That is what we did after having some issues with the format.
