### ISSUE TITLE
Code-Review-Session-30-Oct: Changes Required

### ISSUE THREAD

**Issue by 0x1100010010** [wazih237/New-york-times#7]
Good work guys, The code looks good overall. Only need to fix absolute links so that your assets are visible.

- It's a good practice to put all assets|resources in the assets folder i.e. `/images` directory should be in `/assets/images`.
- Change your path for HTML image and SVG links to absolute path i.e. `/assets/images` to `./assets/images`.
- Change your path for style.css to absolute for all assets i.e.  `/assets/images` to `./../assets/images` as your `style.css` resides in **css** directory.

And that's all guys. Keep up the good work!

**Comment by HillaryOkello** [comment]
Thank you @bashforger, I have implemented the changes you suggested.
